version: 2
jobs:
  build:
    docker:
      -
        image: circleci/ruby:2.5.1-node-browsers
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 4
          BUNDLE_PATH: vendor/bundle
          RACK_ENV: test

    steps:
      - checkout

      # bundler
      -
        type: cache-restore
        key: bundle-{{ checksum "Gemfile.lock" }}
      -
        run: bundle check || bundle install
      -
        type: cache-save
        key: bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # rspec
      -
        type: shell
        command: bundle exec rspec --format progress --format RspecJunitFormatter --out tmp/rspec/rspec.xml

      # results
      -
        type: test-results-store
        path: tmp/rspec

      # artifacts
      -
        type: artifacts-store
        path: coverage
        destination: coverage

      # artifacts
      -
        type: artifacts-store
        path: tmp/rubocop.html
        destination: rubocop.html
